import { Link } from 'react-router-dom'

export default function Terms() {
  return (
    <div className="min-h-screen bg-gray-100">
      <div className="bg-white shadow-sm">
        <div className="max-w-3xl mx-auto px-4 py-3 flex justify-between items-center">
          <Link to="/" className="font-semibold text-gray-800">Content Curator</Link>
          <Link to="/" className="text-blue-600 hover:text-blue-800 text-sm">Back to App</Link>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-gray-800 mb-8">Terms of Service</h1>

        <div className="bg-white rounded-lg shadow p-8 space-y-6 text-gray-600">
          <p className="text-sm text-gray-500">Last updated: January 2025</p>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using Content Curator, you agree to be bound by these Terms of Service. If you do not agree, please do not use our service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">2. Description of Service</h2>
            <p>Content Curator is an AI-powered social media content generation tool designed for marketing professionals and agencies. We use AI technology to help generate content suggestions for various social media platforms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">3. User Responsibilities</h2>
            <p>You are responsible for:</p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              <li>Maintaining the confidentiality of your account</li>
              <li>All activities that occur under your account</li>
              <li>Ensuring generated content complies with applicable laws and platform guidelines</li>
              <li>Reviewing and editing AI-generated content before publishing</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">4. AI-Generated Content</h2>
            <p>Content generated by our AI is provided as suggestions only. You are solely responsible for reviewing, editing, and approving all content before use. We do not guarantee the accuracy, appropriateness, or effectiveness of AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">5. Subscription and Billing</h2>
            <p>Subscriptions are billed in advance on a monthly or yearly basis. You may cancel your subscription at any time through your account settings. Refunds are handled on a case-by-case basis.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">6. Limitation of Liability</h2>
            <p>Content Curator is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service or any content generated through the service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">7. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">8. Contact</h2>
            <p>For questions about these terms, contact us at alharris603@gmail.com.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
